In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("ALL.csv", parse_dates=["Date_time"])
df.head(5)

,Date_time,BO1013_FLOW1,BO1016_Pressure(m),BO1017_Pressure(m),BO1021_FLOW1),BO1021_Pressure,BO1022_flow1,BO1022_Pressure(m),BO1017_FLOW1,BO1029_FLOW1,...,NB1019_Pressure,NB1020_FLOW1,NB1021_FLOW1,NB1022_FLOW1,TD1029_flow1,TD1029_Pressure,TD1043_FLOW1,TD1043_Press(m),NMNBOOTM1_FLOW1,BOO_TM2_Pressure
0,2023-09-15 00:00:00,612.8,21.859,20.275,1613.08,13.078,398.4,19.898,3232,201.6,...,17.894,402.0,1672,397.2,231.2,14.863,670.0,24.0,9720.001,12.631
1,2023-09-15 00:15:00,598.0,22.080,20.556,1540.28,13.038,341.2,20.008,3200,175.2,...,18.245,370.0,1576,360.0,196.4,14.659,577.6,24.0,9000.001,12.600
2,2023-09-15 00:30:00,585.2,22.268,20.816,1558.08,13.039,344.4,20.462,3168,175.6,...,18.620,356.0,1596,355.2,171.6,14.855,541.2,24.0,8800.001,12.600
3,2023-09-15 00:45:00,574.0,22.453,21.028,1549.68,13.062,354.4,20.642,3080,152.0,...,18.841,361.6,1612,364.8,173.2,14.855,542.8,24.0,8640.001,12.631
4,2023-09-15 01:00:00,557.6,22.659,21.274,1442.48,13.023,362.8,20.877,3076,144.0,...,19.191,352.0,1608,368.8,150.8,14.926,526.0,24.0,8480.001,12.631

In [2]:
new_index = pd.date_range(start = df["Date_time"].min(), end = df["Date_time"].max(), freq = "5T" )
new_df = pd.DataFrame(new_index, columns=['Date_time'])
new_df.head(5)

            Date_time
0 2023-09-15 00:00:00
1 2023-09-15 00:05:00
2 2023-09-15 00:10:00
3 2023-09-15 00:15:00
4 2023-09-15 00:20:00

In [9]:
# Kết hợp DataFrame mới với DataFrame gốc
merged_df = pd.merge(new_df, df, how='left', on='Date_time')
feature = merged_df.drop("Date_time", axis = 1).columns
# Nội suy tuyến tính trên các khoảng thời gian cụ thể
merged_df[feature] = merged_df[feature].interpolate(method='linear')
# merged_df[feature] = merged_df[feature].interpolate(method='linear interp')
merged_df.to_csv("ALL_5T.csv")
print(merged_df.columns)

Index(['Date_time', 'BO1013_FLOW1', 'BO1016_Pressure(m)', 'BO1017_Pressure(m)',
       'BO1021_FLOW1)', 'BO1021_Pressure', 'BO1022_flow1',
       'BO1022_Pressure(m)', 'BO1017_FLOW1', 'BO1029_FLOW1',
       'BO1029_Pressure(m)', 'NB1013_FLOW1', 'NB1017_FLOW1', 'NB1017_Pressure',
       'NB1019_FLOW1', 'NB1019_Pressure', 'NB1020_FLOW1', 'NB1021_FLOW1',
       'NB1022_FLOW1', 'TD1029_flow1', 'TD1029_Pressure', 'TD1043_FLOW1',
       'TD1043_Press(m)', 'NMNBOOTM1_FLOW1', 'BOO_TM2_Pressure'],
      dtype='object')